import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Provider from "@/components/Provider";
import ApiProvider from "@/context/ApiProvider";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import StripeProvider from "@/components/StripeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        {/*<QueryClientProvider client={queryClient}>*/}
        <ApiProvider>
          <StripeProvider>
            <body className={inter.className}>{children}</body>
          </StripeProvider>
        </ApiProvider>
        {/* </QueryClientProvider>*/}
      </Provider>
    </html>
  );
}
